export const FETCH_LISTS = 'FETCH_LISTS';
export const POST_LIST = 'POST_LIST'
export const DELETE_LIST = 'DELETE_LIST';
export const UPDATE_LIST = 'UPDATE_LIST';
export const SELECT_LIST = 'SELECT_LIST';
export const REMOVE_SELECT_LIST = 'REMOVE_SELECT_LIST';

export const FETCH_ITEMS = 'FETCH_ITEMS';
export const POST_ITEM = 'POST_ITEM';
export const DELETE_ITEM ='DELETE_ITEM';
export const UPDATE_ITEM = 'UPDATE_ITEM';
export const SELECT_ITEM_LIST_DATA = 'SELECT_ITEM_LIST_DATA';
export const REMOVE_ITEM_LIST_DATA = 'REMOVE_ITEM_LIST_DATA';
export const CHECK_SELECT_ITEM = 'CHECK_SELECT_ITEM';